### ISSUE TITLE
Lint crash related to slack.lint.compose.ModifierReusedDetector after updating to 1.5.0

### ISSUE THREAD

**Issue by w2sv** [slackhq/compose-lints#556]
After updating to 1.5.0 and running ./gradlew check I get the following error message:

```
> Task :modules:designsystem:lintAnalyzeDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':modules:designsystem:lintAnalyzeDebug' (registered by plugin 'com.android.internal.library').
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintWorkAction
   > Unexpected failure during lint analysis (this is a bug in lint or one of the libraries it depends on)
     
     Message: Unexpected failure during lint analysis (this is a bug in lint or one of the libraries it depends on)
     
     Message: Unexpected failure during lint analysis of Buttons.kt (this is a bug in lint or one of the libraries it depends on)
     
     Message: 'java.lang.Object java.util.List.removeLast()'
     
     The crash seems to involve the detector \\\`slack.lint.compose.ModifierReusedDetector\\\`.
     You can try disabling it with something like this:
         android {
             lint {
                 disable "ComposeModifierReused"
             }
         }
     
     Stack: \\\`NoSuchMethodError:CodeFlowAnalysisKt$toSimplifiedCfaAst$blockStack$1.exitBlock(CodeFlowAnalysis.kt:233)←CodeFlowAnalysisKt$toSimplifiedCfaAst$1.afterVisitBlockExpression(CodeFlowAnalysis.kt:259)←UBlockExpression.accept(UBlockExpression.kt:22)←UMethod.accept(UMethod.kt:45)←CodeFlowAnalysisKt.toSimplifiedCfaAst(CodeFlowAnalysis.kt:247)←CodeFlowAnalysisKt.buildCodeFlowGraph(CodeFlowAnalysis.kt:164)←ModifierReusedDetector.visitComposable(ModifierReusedDetector.kt:66)←ComposableFunctionDetector$createUastHandler$1.visitMethod(ComposableFunctionDetector.kt:36)←UElementVisitor$DispatchUastVisitor.visitMethod(UElementVisitor.kt:531)←UElementVisitor$DelegatingUastVisitor.visitMethod(UElementVisitor.kt:800)←UMethod.accept(UMethod.kt:42)←ImplementationUtilsKt.acceptList(implementationUtils.kt:15)←AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:223)←ImplementationUtilsKt.acceptList(implementationUtils.kt:15)←UFile.accept(UFile.kt:89)←UastLintUtilsKt.acceptSourceFile(UastLintUtils.kt:956)←UElementVisitor$visitFile$3.run(UElementVisitor.kt:205)←LintClient.runReadAction(LintClient.kt:1655)←LintCliClient.runReadAction(LintCliClient.kt:228)←LintDriver$LintClientWrapper.runReadAction(LintDriver.kt:2694)←UElementVisitor.visitFile(UElementVisitor.kt:202)←LintDriver$visitUastDetectors$1.run(LintDriver.kt:2032)←LintClient.runReadAction(LintClient.kt:1655)←LintCliClient.runReadAction(LintCliClient.kt:228)←LintDriver$LintClientWrapper.runReadAction(LintDriver.kt:2694)←LintDriver.visitUastDetectors(LintDriver.kt:2030)←LintDriver.visitUast(LintDriver.kt:1977)←LintDriver.runFileDetectors(LintDriver.kt:1234)←LintDriver.checkProject(LintDriver.kt:1041)←LintDriver.checkProjectRoot(LintDriver.kt:607)←LintDriver.access$checkProjectRoot(LintDriver.kt:179)←LintDriver$analyzeOnly$1.invoke(LintDriver.kt:434)←LintDriver$analyzeOnly$1.invoke(LintDriver.kt:431)←LintDriver.doAnalyze(LintDriver.kt:490)←LintDriver.analyzeOnly(LintDriver.kt:431)←LintCliClient$analyzeOnly$1.invoke(LintCliClient.kt:261)←LintCliClient$analyzeOnly$1.invoke(LintCliClient.kt:258)←LintCliClient.run(LintCliClient.kt:307)←LintCliClient.analyzeOnly(LintCliClient.kt:258)←Main.run(Main.java:1788)←Main.run(Main.java:287)←NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)←NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)←DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)←Method.invoke(Method.java:569)←AndroidLintWorkAction.invokeLintMainRunMethod(AndroidLintWorkAction.kt:103)←AndroidLintWorkAction.runLint(AndroidLintWorkAction.kt:90)←AndroidLintWorkAction.execute(AndroidLintWorkAction.kt:64)←DefaultWorkerServer.execute(DefaultWorkerServer.java:68)←NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:64)←NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:61)←ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:102)←NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:61)←AbstractWorker$1.call(AbstractWorker.java:44)←AbstractWorker$1.call(AbstractWorker.java:41)←DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:210)←DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:205)←DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:67)←DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:60)←DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:167)←DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:60)←DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:54)←AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)←NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:58)←DefaultWorkerExecutor.lambda$submitWork$0(DefaultWorkerExecutor.java:174)←FutureTask.run(FutureTask.java:264)←DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:191)←DefaultConditionalExecutionQueue$ExecutionRunner.access$500(DefaultConditionalExecutionQueue.java:112)←DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:168)←Factories$1.create(Factories.java:30)←DefaultWorkerLeaseService.lambda$runAndReleaseLocks$0(DefaultWorkerLeaseService.java:300)←ResourceLockStatistics$1.measure(ResourceLockStatistics.java:43)←DefaultWorkerLeaseService.runAndReleaseLocks(DefaultWorkerLeaseService.java:298)←DefaultWorkerLeaseService.withLocksAcquired(DefaultWorkerLeaseService.java:294)←DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:286)←DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:130)←DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:135)←DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:163)←DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:125)←Executors$RunnableAdapter.call(Executors.java:539)←FutureTask.run(FutureTask.java:264)←ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)←AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)←ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)←ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)←Thread.run(Thread.java:840)\\\`
```

After downgrading to 1.4.3 everything runs through smoothly once again. 

Offending file: 

```kotlin
package com.w2sv.designsystem

import androidx.compose.foundation.BorderStroke
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.ElevatedButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

@Composable
fun DialogButton(
    text: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    contentColor: Color = MaterialTheme.colorScheme.secondary,
    containerColor: Color = MaterialTheme.colorScheme.surfaceContainerLow,
    enabled: Boolean = true
) {
    ElevatedButton(
        onClick = onClick,
        modifier = modifier,
        enabled = enabled,
        border = if (enabled) {
            BorderStroke(
                Dp.Hairline,
                contentColor
            )
        } else {
            null
        },
        elevation = ButtonDefaults.elevatedButtonElevation(8.dp),
        colors = ButtonDefaults.elevatedButtonColors(contentColor = contentColor, containerColor = containerColor)
    ) {
        Text(text = text)
    }
}

@Composable
fun HighlightedDialogButton(
    text: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    enabled: Boolean = true
) {
    DialogButton(
        text = text,
        onClick = onClick,
        enabled = enabled,
        modifier = modifier,
        containerColor = MaterialTheme.colorScheme.primaryContainer,
        contentColor = MaterialTheme.colorScheme.onPrimaryContainer
    )
}

```

Shouldn't even cause a lint error as far as I can see.

**Comment by ZacSweers** [comment]
Thanks for the report. If you use JDK 21 in the meantime that should work, we'll fix this in the next release
